### ISSUE TITLE
Ameli Reyes Hernández 1B

### ISSUE THREAD

**Issue by AmeliReyesHernandez** [SistemasTecTlaxiaco/actividad-1-mapa-mental-AmeliReyesHernandez#1]
![Investigación documental](https://user-images.githubusercontent.com/112219336/187792360-7050b041-5b32-4e00-8602-59cb9949a7d6.jpeg)

**Comment by Daisy-GonzalezLita12** [comment]
18.5

**Comment by josealfredo79** [comment]
Debe ser calificación entre 0 y 20 por favor...

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
